spring.application.name=Ap

# ===============================
# THYMELEAF (optional tweak)
# ===============================
spring.thymeleaf.cache=false

# ===============================
# H2 DATABASE CONFIG
# ===============================
spring.datasource.url=JDBC:h2:file:./data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Show SQL in console (great for teaching)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true